### ISSUE TITLE
Error in installing?

### ISSUE THREAD

**Issue by ygoncho** [spf13/spf13-vim#203]
Hi,
Sorry, I'm a bit of a newb, bit I wanted to install spf13
I ran the command:
curl --insecure http://j.mp/spf13-vim3 -L -o - | sh
and getting this error:

"-stdin-" 1L, 1C
Press ENTER or type command to continue   

after I hit enter:
Error detected while processing function vundle#installer#new..<SNR>15_process..vundle#installer#run..vundle#installer#install..<SNR>15_syn
c:
line   14:
E117: Unknown function: shellescape
E15: Invalid expression: 'git clone --recursive '.a:bundle.uri.' '.shellescape(a:bundle.path())
Error detected while processing function vundle#installer#new..<SNR>15_process:
line   13:
E121: Undefined variable: g:vundle_last_status

**Comment by spf13** [comment]
Which OS and shell?

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by ygoncho** [comment]
Is this helpful?

SUSE LINUX Enterprise Server 10 (x86_64) Release 10
tcsh

On Wed, Nov 14, 2012 at 6:47 PM, Steve Francia notifications@github.comwrote:

> Which OS and shell?
> 
> ## 
> 
> Steve Francia
> http://stevefrancia.com
> http://spf13.com
> http://twitter.com/spf13
> 
> On Thu, Nov 8, 2012 at 10:25 AM, ygoncho notifications@github.com
> wrote:
> 
> > Hi,
> > Sorry, I'm a bit of a newb, bit I wanted to install spf13
> > I ran the command:
> > curl --insecure http://j.mp/spf13-vim3 -L -o - | sh
> > and getting this error:
> > 
> > "-stdin-" 1L, 1C
> > Press ENTER or type command to continue
> > 
> > after I hit enter:
> > Error detected while processing function
> > 
> > vundle#installer#new..15_process..vundle#installer#run..vundle#installer#install..15_syn
> > 
> > c:
> > line 14:
> > E117: Unknown function: shellescape
> > E15: Invalid expression: 'git clone --recursive '.a:bundle.uri.'
> > '.shellescape(a:bundle.path())
> > Error detected while processing function
> > vundle#installer#new..15_process:
> > line 13:
> > E121: Undefined variable: g:vundle_last_status
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/spf13/spf13-vim/issues/203>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/203#issuecomment-10373408.

## 

-=-

Yuval Gonczarowski

ygoncho@gmail.com

**Comment by spf13** [comment]
I don't think we've done much testing with tcsh. Mostly with bash and zsh. I don't know why it wouldn't work, but I would try a different shell and see if that works for you. At least then we would know that it's something to do with tcsh.    

## 

Steve Francia
@spf13

**Comment by ygoncho** [comment]
Just tried installing on both bash and zsh, same errors... :(

**Comment by spf13** [comment]
We fixed an issue with the install command in 22798b6571a044e02897c78d32ac6c535c72a91d, can you try it again and see if it works now?

**Comment by ygoncho** [comment]
Hi, thanks!

I still get many errors like this:

Error detected while processing function
vundle#installer#new..<SNR>15_process..vundle#installer#run..vundle#installer#install..<SNR>15_syn
c:
line   14:
E117: Unknown function: shellescape
E15: Invalid expression: 'git clone --recursive '.a:bundle.uri.'
'.shellescape(a:bundle.path())

On Wed, Nov 28, 2012 at 1:24 AM, Steve Francia notifications@github.comwrote:

> We fixed an issue with the install command in 22798b6https://github.com/spf13/spf13-vim/commit/22798b6571a044e02897c78d32ac6c535c72a91d,
> can you try it again and see if it works now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spf13/spf13-vim/issues/203#issuecomment-10782462.

## 

-=-

Yuval Gonczarowski

ygoncho@gmail.com

**Comment by spf13** [comment]
I think we have resolved this in the latest release. Please confirm and reopen if issues persist.

**Comment by X4** [comment]
@ygoncho that is no error in our installer, the error happens because you may have a  too old version of vim installed. It's required to at least have Vim version 7.2 in order to use vundle and the internal shellescape functions.
Just tell us the output of: `LANG=C vim --version`
You should get something like this:

``` bash,
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May  6 2013 17:43:58)
Included patches: 1-905
Modified by Gentoo-7.3.905
Compiled by root@orion
Huge version without GUI.  Features included (+) or not (-):
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
-dnd             +modify_fname    +signs           +xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    
+farsi           +mouse_netterm   +syntax          
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -march=x86-64 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: x86_64-pc-linux-gnu-gcc   -Wl,-E  -Wl,-O1 -Wl,--as-needed -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lelf -lnsl   -lcurses -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-O1 -Wl,--as-needed  -L/usr/lib64/perl5/5.12.4/x86_64-linux-thread-multi/CORE -lperl -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
```
