### ISSUE TITLE
Easytags error

### ISSUE THREAD

**Issue by cobhimself** [spf13/spf13-vim#3]
bundle/easytags/autoload/easytags.vim: Vim(call):E117: Unknown function: xolox#debug (at function easytags#autoload..easytags@update..44_run_ctags, line 3

Does anyone know what is causing this error? The error above is shown periodically in vim and, whenever I'm in insert mode and press backspace, I get this error:

=DelimitMate_BS() E117: Unknown function: DelimitMate_BS

**Comment by spf13** [comment]
I fixed the easy tags error a day or two ago. You need to make sure that your submodule is pulling from my easytags fork. You may need to do 'git submodule sync' to make sure it's pointing at the correct repo. 

The DelimateMate issue is an issue with the plugin. I'm looking into it.

**Comment by spf13** [comment]
cobhimself: I'll close this issue. since the topic is actually closed. Can you create the DelimitMate issue in a separate thread so we can track it separately.

**Comment by cobhimself** [comment]
I synced the submodules and the error still appeared. So, I started from scratch and how I get a similar error but slightly different (51_run_ctags instead of 44_run_ctags).

bundle/easytags/autoload/easytags.vim: Vim(call):E117: Unknown function: xolox#debug (at function easytags#autoload..easytags#update..<SNR>51_run_ctags, line 3)

**Comment by spf13** [comment]
I can't reproduce that. Can you tell me which remote and hash your easytags is pointing at?
