### ISSUE TITLE
clipboard=unnamedplus is breaking my .vim startup

### ISSUE THREAD

**Issue by lukedomanski** [spf13/spf13-vim#564]
@johntyree 
This commit 47547b854117e9414b68f4363ac5c454fc098a2a at line 73, or this one (unlikely) c5addb92e07146d59cf217ae563ea15d98df0efa at line 73, seems to have broken my loading of vim in all of the following:
- Remote Linux terminal via Putty
- Local gnome-terminal in X
- Local xterm terminal in X

with error:

```
Error detected while processing $HOME/.vimrc:
line   75:
E474: Invalid argument: clipboard=unnamedplus
Press ENTER or type command to continue
```

replacing `if Linux()` with the previous `if has('x') && has ('gui')` solves the problem for me.

**Comment by johntyree** [comment]
What's the output of `vim --version` for you? Maybe you don't have
`+clipboard` ?

Gvim _always_ has it, but some distros package the two separately to
allow machines with X installed at all to just install vim.

2014-02-17 18:06 UTC−06:00, Luke Domanski notifications@github.com:

**Comment by lukedomanski** [comment]
Vim 7.3 and it has +clipboard enabled.

But wouldn't the has('clipboard') check cover that anyway? Perhaps +clipboard should NOT be compiled for terminal use?

**Comment by johntyree** [comment]
OK I see, it is `+X11` that's required there, not `+clipboard`.  I assume your terminal vim doesn't have `+X11`?

In any case, you're right, that line needs to change.

**Comment by johntyree** [comment]
@lukedomanski should work now. [Test that PR](https://help.github.com/articles/checking-out-pull-requests-locally) with `git checkout pr/565` in your spf13 repo.

**Comment by lukedomanski** [comment]
Thanks ill check tonight. I'm suspecting it doesn't have +X11, it is on a headless  login node of a compute cluster. I'll check anyway.

Regards,
Luke Domanski

**Comment by lukedomanski** [comment]
I lied, I didn't test it last night :)

Anyway, that pull request does not solve the problem. I checked `vim --version` again, and noted that:
- `+X11` is present, and `:echo has('X11')` prints `1` (makes sense)
- `+gui` is **not** present, **but** `:echo has('gui')` prints `1`! (so obviously this is set by another compile feature)
- `:echo has('gui_running')` prints `0` (make sense, this might be our winner)
- `+x` is **not** present, and `:echo has('x')` prints `0` (makes sense), but then again...i dont think "x" is a feature anymore??

So, the original `if has('x') && has ('gui')` "solves" the problem, but only because `has('x')` probably always returns `0`.

`if has('X11') && has('gui')` does **not** solve the problem, maybe because it does not allow for the fact that a vim version is compiled for dual use with terminal-only and gui.  

`if has('gui_running')` solved the problem _on the system I'm using_, but this does not mean that `has('clipboard') && has('gui_running')` is the only situation in which `clipboard=unnamedplus` is invalid. An interesting feature that might have relevance is `+xterm_clipboard`, see docs in `:help 'clipboard'`,

Interestingly, `:helpgrep unnamedplus` only turned up results in the changelog of the YankRing.txt file. So on a whim I uninstalled YankRing and tried again...still not fixed. I could not find documentation for it anywhere else in vim.

**Comment by lukedomanski** [comment]
http://vim.wikia.com/wiki/Accessing_the_system_clipboard says that `unnnamedplus` is available from 7.3.34. ~~How do i confirm my patch number? The one after the second "."~~ (found it, http://www.packtpub.com/article/vim-7-2-scripting, as per `:help v:version`)

`has('patch34')` returns `0` for me, maybe I have not got the appropriate patch installed?

**Comment by johntyree** [comment]
@lukedomanski `vim --version` and look at the `Included Patches` line. The highest patch is your minor version.

**Comment by johntyree** [comment]
@lukedomanski funny enough, the help says right there. 

```
            Availability can be checked with: >
                if has('unnamedplus')
```

I'll update the PR.

**Comment by lukedomanski** [comment]
@johntyree 
"vim --version and look at the Included Patches line. The highest patch is your minor version."

Okay, so it looks like the version of 7.3 installed on the system I'm logged into has no patches applied. As it does not have an Included Patches section. I looked at version 7.2 output on this system to check against 7.3 output, and it did have an "Included Patches" section.

"funny enough, the help says right there.

```
            Availability can be checked with: >
                if has('unnamedplus')
```

I'll update the PR."

Thanks. Yeah that is not in my help/docs, so a backwards compatibility check like that is a good idea for those people logging in to multiple systems that have little control over the install.

**Comment by lukedomanski** [comment]
Cheers! it works see #565
